services:
  - type: web
    name: revoscope-api
    runtime: python
    plan: free
    rootDir: API
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CORS_ORIGINS
        value: '["https://chronostrike.elouanbahri.com"]'
      - key: BINANCE_TESTNET
        value: "true"
